name = "HEXA_TopOpt"
uuid = "ca0ed32d-1ad4-4b7a-9919-fa42dfec13a8"
authors = ["User"]
version = "1.0.0"

[deps]
AMGX = "c963dde9-0319-47f5-bf0c-b07d3c80ffa6"
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
MarchingCubes = "299715c1-40a9-479a-aaf9-4a633d36f717"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
AMGX = "0.2.0"
AlgebraicMultigrid = "1.1.0"
ArgParse = "1.2.0"
CUDA = "5.9.5"
Dates = "1.11.0"
JSON = "0.21.4"
JSON3 = "1.14.3"
Krylov = "0.10.3"
LinearAlgebra = "1.11.0"
LinearOperators = "2.11.0"
MarchingCubes = "0.1.11"
Printf = "1.11.0"
SparseArrays = "1.11.0"
Statistics = "1.11.1"
YAML = "0.4.16"
julia = "1.9"
